name: Test

on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: set up laravel
              uses: laravel/actions/setup-laravel@v3
              with:
                php-version: '8.2'
                extensions: mbstring, curl, dom, fileinfo, json, mbstring, openssl, pdo, tokenizer
            - name: run tests
              run: composer test