name: Test

on:
    push:
        branches:
            - develop

jobs:
    test_php_8_2:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up PHP 8.2
              uses: php-actions/setup-php@v4
              with:
                  php-version: '8.2'
                  extensions: mbstring, curl, dom, fileinfo, json, mbstring, openssl, pdo, tokenizer